
logging:
  level:
    spring.board.myBoard: debug
    org.springframework.web.servlet: debug #resp,req 부분만 debugging 하겠다.
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board #datasource url
    username: victor
    password: 1q2w3e4r
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver # h2 사용 방법
  jpa:
    defer-datasource-initialization: true # test용 db 만들수 있게 하기 resources 부분 data.sql
    show-sql: true # sql문장 쿼리 보여줄까
    hibernate:
      ddl-auto: create # 엔티티 보고 자동으로 테이블 데이터 유추, 자동으로 ddl 문을 만든다. => create 문을 자동으로 마듬
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100 # jpa 복잡한 쿼리 => 한번에 벌크로 select => n+1 쿼리 문제 => 100개 단위로 셀렉
      h2.console.enabled: true # inMemoryDB로 사용할 예정
      sql.init.mode: always # data.sql을 언제 작동시킬꺼냐
  config:
    activate:
      on-profile:
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
debug: false #각종 debug
management.endpoints.web.exposure.include: "*" #actuactor endpoint 감춰져 있는거 활성활

---
# 위에 --- 이 라인으로 document를 새로 만들 수 있다.
spring:
  config:
    activate:
      on-profile: testdb
  datasource:
    url: jdbc:h2:mem:board;mode=mysql #
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  test.database.replace: none #사용 안할 시 =>전역 설정 @AutoConfigureTestDatabase 안써도 된다.

# 테스트 DB용
